name: exponea
description: >-
  A full featured wrapper for Exponea SDK that supports Android and iOS.
version: 0.2.1
homepage: https://exponea.com
repository: https://github.com/exponea/exponea-flutter-sdk

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.exponea
        pluginClass: ExponeaPlugin
      ios:
        pluginClass: ExponeaPlugin
